### ISSUE TITLE
添加主机失败

### ISSUE THREAD

**Issue by xiaoluoge11** [CloudWise-OpenSource/OMP#32]
添加主机提示创建分区失败:
[2022-07-05 17:24:04,053][ERROR] ./utils/exception_handler.py 33 -> ExceptionResponse: {'data_folder': [ErrorDetail(string='创建数据分区操作失败', code='invalid')]}; {'view': <hosts.views.HostListView object at 0x7f4e67fe5c70>, 'args': (), 'kwargs': {}, 'request': <rest_framework.request.Request: POST '/api/hosts/hosts/'>}
[2022-07-05 17:24:04,054][ERROR] ./utils/exception_handler.py 34 -> ExceptionResponse: Traceback (most recent call last):
  File "/data/omp/component/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/omp/component/env/lib/python3.8/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/data/omp/component/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'data_folder': [ErrorDetail(string='创建数据分区操作失败', code='invalid')]}

**Comment by Xiaoyuerwise** [comment]
添加主机建议使用root用户执行
如果使用的是普通用户，请根据前端提示信息，手动执行主机初始化，或修改相关配置信息
